on:
  push:

    tags:
      - 'v*' 
    branches:
        - "main"

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

      - name: Upload release artifacts
        uses: Roang-zero1/github-upload-release-artifacts-action@v2
        with:
          args: "dist/bin/ dist/shell/compiled.sh"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          body: |
            Changes in this Release
            - First Change:
            - Second Change:
          draft: false
          prerelease: false